#ifndef QUADR_VERSION_H
#define QUADR_VERSION_H

#define QUADR_VERSION_MAJOR   1
#define QUADR_VERSION_MINOR   5
#define QUADR_VERSION_PATCH   0
#define QUADR_VERSION_STRING  "1.5.0"
#define QUADR_PROTOCOL_VER    0x15

#endif /* QUADR_VERSION_H */
